- vendordeps/Phoenix.json
(cherry picked from commit b67de6e9093c1f730cb3528a9540623ade7d7622)
> Add Phoenix dependency

- src/main/java/frc/robot/Main.java
- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/actuators/ExampleActuator.java
- src/main/java/frc/robot/groupcommands/ExampleGroupCommand.java
- src/main/java/frc/robot/sensors/ExampleSensor.java
- src/main/java/frc/robot/telemetries/MultipleOutputStream.java
- src/main/java/frc/robot/telemetries/Trace.java
- src/main/java/frc/robot/telemetries/TracePair.java
Also added the telemetries code from last year. I put dummy files into each new package, but we can get rid of those later.
> Added new packages and made robot a singleton

- src/main/java/frc/robot/subsystems/drivetrain/RealDriveTrain.java
Add drivetrain stuff
uses sparkmax controller
> DriveTrain

- src/main/java/frc/robot/actuators/DoubleSolenoid4905.java
Also methods for extend/retract piston w/ it
> Made class for Double Solenoid (DoubleSolenoid4905)

- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/drivetrain.conf
- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/subsystems/SubsystemsContainer.java
- src/main/java/frc/robot/subsystems/drivetrain/DriveTrain.java
we got the drive train working
> we added a setDefaultCommands.

- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/commands/DriveBackwardTimed.java
- src/main/java/frc/robot/oi/OIContainer.java
- src/main/java/frc/robot/oi/Smartdashboard.java
We also added Subsystem container to OIContainer.
We created drive backward command.
> We added subsystem container to Smartdashboard.

- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/drivetrain.conf
- src/main/java/frc/robot/oi/DriveController.java
- src/main/java/frc/robot/oi/SubsystemController.java
- src/main/java/frc/robot/subsystems/drivetrain/DriveTrain.java
- src/main/java/frc/robot/subsystems/drivetrain/MockDriveTrain.java
- src/main/java/frc/robot/subsystems/drivetrain/RealDriveTrain.java
> Move with gyro correct

- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/commands/DoNothingAuto.java
- src/main/java/frc/robot/commands/DriveBackwardTimed.java
- src/main/java/frc/robot/oi/OIContainer.java
- src/main/java/frc/robot/oi/SmartDashboard4905.java
> Auto selector

- src/main/java/frc/robot/lib/ButtonsEnumerated.java
- src/main/java/frc/robot/lib/EnumeratedRawAxis.java
- src/main/java/frc/robot/lib/POVDirectionNames.java
We added POVDirectionNames from last years code to this years code.
> We Added Buttons Enumerated raw axis.

- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/sensors.conf
- src/main/java/frc/robot/sensors/ballfeedersensor/RealBallFeederSensor.java
- src/main/java/frc/robot/subsystems/SubsystemsContainer.java
- src/main/java/frc/robot/subsystems/feeder/MockFeeder.java
- src/main/java/frc/robot/subsystems/feeder/RealFeeder.java
Master had several errors. This fixes them
Tested on The Claw and The Droid We're Looking For
> fix(many): Fix master

- src/main/deploy/robotConfigs/RoadKill/drivetrain.conf
- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/drivetrain.conf
- src/main/java/frc/robot/actuators/SparkMaxController.java
Set the current limit for the NEOs in accordance with Bill's email
> Set Current Limit

- src/main/deploy/robotConfigs/RoadKill/Shooter.conf
- src/main/deploy/robotConfigs/TheClaw/Shooter.conf
- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/Shooter.conf
- src/main/java/frc/robot/Config4905.java
- src/main/java/frc/robot/commands/pidcommands/RunShooterSeriesVelocity.java
- src/main/java/frc/robot/commands/pidcommands/RunShooterWheelVelocity.java
- src/main/java/frc/robot/groupcommands/parallelgroup/DefaultShooterParallelCommandGroup.java
- src/main/java/frc/robot/groupcommands/parallelgroup/ShooterParallelSetShooterVelocity.java
- src/main/java/frc/robot/oi/SubsystemController.java
- src/main/java/frc/robot/subsystems/SubsystemsContainer.java
I tested this on roadkill prior to merging master in. This code should be tested on roadkill and claw in its current state
> Adding shooting command

- src/main/deploy/robotConfigs/RoadKill/drivetrain.conf
- src/main/deploy/robotConfigs/TheClaw/drivetrain.conf
- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/drivetrain.conf
- src/main/java/frc/robot/commands/TeleOpCommand.java
- src/main/java/frc/robot/oi/DriveController.java
This was put in the wrong branch but I didnt want to figure out how to put it on another branch soooo.
> Added slow mode (on the wrong branch)

- src/main/deploy/robotConfigs/RoadKill/Intake.conf
- src/main/deploy/robotConfigs/TheClaw/Intake.conf
The intake speed needed to be added to roadkills config
> Config fix for broken master (Dont tell Sean)

- src/main/java/frc/robot/commands/DeployAndRunIntakeStarter.java
- src/main/java/frc/robot/groupcommands/DeployAndRunIntake.java
- src/main/java/frc/robot/sensors/ballfeedersensor/MockBallFeederSensor.java
- src/main/java/frc/robot/subsystems/climber/MockClimber.java
- src/main/java/frc/robot/subsystems/climber/RealClimber.java
- src/main/java/frc/robot/subsystems/feeder/MockFeeder.java
- src/main/java/frc/robot/subsystems/feeder/RealFeeder.java
- src/main/java/frc/robot/subsystems/intake/MockIntake.java
- src/main/java/frc/robot/subsystems/intake/RealIntake.java
Please don't leave auto-generated TODOs in your code from now on 😭
> Removed TODOs

- build.gradle
Might also want to look at bumping gradle version? IDK
> chore(wpilib): Bump WPILib version

- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/pidconstants.conf
- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/sensors.conf
- src/main/java/frc/robot/commands/pidcommands/TurnToFaceCommand.java
- src/main/java/frc/robot/sensors/limelightcamera/RealLimelightCamera.java
- src/main/limelight/Pipeline_Name.vpr
> Fixes the limelight, should be perfectly angled for interior target :D

- src/main/java/frc/robot/commands/pidcommands/MoveUsingEncoder.java
- src/main/java/frc/robot/oi/AutoModes4905.java
- src/main/java/frc/robot/pidcontroller/PIDController4905.java
I wrote the auto mode for nav challenge 1
> Nav challenge1

- src/main/java/frc/robot/groupcommands/athomechallengepathways/GalacticSearchPathA.java
- src/main/java/frc/robot/groupcommands/athomechallengepathways/GalacticSearchPathB.java
- src/main/java/frc/robot/oi/SmartDashboard4905.java
Need to test GalacticSearchPathB.java to make sure that that path is correct. It can be tested by enabling the robot in tele-op and pressing the Galactic Search Path A button on the smart dashboard to run the path. After that I think this is good to be merged into master.
> Galactic search challenge baseline

- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/Shooter.conf
- src/main/deploy/robotConfigs/TheDroidYoureLookingFor/commandconstants.conf
> Update pid constants

- build.gradle
openning this PR as a new PR to test email notification
> update to WPILIB 2022.2.1

- src/main/java/frc/robot/commands/feederCommands/RunFeeder.java
- src/main/java/frc/robot/commands/shooterCommands/RunShooterRPM.java
- src/main/java/frc/robot/oi/SubsystemController.java
Fixed problems with eject button
> Fixing eject button

- src/main/deploy/robotConfigs/SAM/drivetrain.conf
- src/main/java/frc/robot/subsystems/samArmExtRet/RealSamArmExtRet.java
> Arm manual extend retract

- src/main/deploy/robotConfigs/ShowBot/commandconstants.conf
- src/main/java/frc/robot/commands/driveTrainCommands/BalanceRobot.java
- src/main/java/frc/robot/commands/groupCommands/samArmRotExtRetCommands/BalancingArmPosition.java
Added balance robot config to showbot Command Constants Config.
> Balance robot sample stop

- src/main/java/frc/robot/commands/driveTrainCommands/DriveBackwardTimed.java
- src/main/java/frc/robot/commands/driveTrainCommands/EnableParkingBrake.java
- src/main/java/frc/robot/commands/driveTrainCommands/MoveUsingEncoder.java
- src/main/java/frc/robot/commands/driveTrainCommands/MoveUsingEncoderTester.java
- src/main/java/frc/robot/commands/driveTrainCommands/MoveWithoutPID.java
- src/main/java/frc/robot/commands/driveTrainCommands/PauseRobot.java
- src/main/java/frc/robot/commands/driveTrainCommands/TankTeleOpCommand.java
- src/main/java/frc/robot/commands/driveTrainCommands/ToggleBrakes.java
- src/main/java/frc/robot/commands/examplePathCommands/DriveTrainDiagonalPath.java
- src/main/java/frc/robot/commands/examplePathCommands/DriveTrainRectangularPath.java
- src/main/java/frc/robot/commands/groupCommands/autonomousCommands/TaxiAuto.java
- src/main/java/frc/robot/commands/groupCommands/romiCommands/AllianceAnticsSimple.java
- src/main/java/frc/robot/commands/groupCommands/romiCommands/RomiChallenge1.java
- src/main/java/frc/robot/commands/romiCommands/CheckRomiVelocityConversionFactor.java
- src/main/java/frc/robot/pathgeneration/pathgenerators/DriveTrainDiagonalPathGenerator.java
- src/main/java/frc/robot/pathgeneration/pathgenerators/DriveTrainRectangularPathGenerator.java
- src/main/java/frc/robot/pathgeneration/pathgenerators/TwoDDriveTrainPathGenerator.java
- src/main/java/frc/robot/subsystems/SubsystemsContainer.java
- src/main/java/frc/robot/subsystems/drivetrain/tankDriveTrain/MockTankDriveTrain.java
- src/main/java/frc/robot/subsystems/drivetrain/tankDriveTrain/RealTankDriveTrain.java
- src/main/java/frc/robot/subsystems/drivetrain/tankDriveTrain/RomiTankDriveTrain.java
- src/main/java/frc/robot/subsystems/drivetrain/tankDriveTrain/SparkMaxTankDriveTrain.java
- src/main/java/frc/robot/subsystems/drivetrain/tankDriveTrain/TalonSRXTankDriveTrain.java
- src/main/java/frc/robot/subsystems/drivetrain/tankDriveTrain/TankDriveTrain.java
- src/main/java/frc/robot/subsystems/ledlights/BillsLEDs.java
- src/main/java/frc/robot/subsystems/ledlights/RealLEDs.java
- src/main/java/frc/robot/subsystems/ledlights/WS2812LEDs.java
The code works and it has been tested on both TopGun and ShowBot.
> Re factored the DriveTrain files into TankDriveTrain files.

- src/main/deploy/robotConfigs/TopGun/shooter.conf
- src/main/java/frc/robot/commands/groupCommands/topGunShooterFeederCommands/ShootLongShot.java
- src/main/java/frc/robot/commands/topGunShooterCommands/MoveShooterAlignment.java
> lowered the angle for long shot because top gun wasn't making it there

- src/main/deploy/robotConfigs/SwerveBot/swervedrivetrain.conf
changed swervebot to use krakens :3
> Made swervebot use krakens

- src/main/deploy/robotConfigs/SBSD/commandconstants.conf
- src/main/deploy/robotConfigs/SBSD/controllers.conf
- src/main/deploy/robotConfigs/SBSD/robot.conf
- src/main/deploy/robotConfigs/SBSD/sensors.conf
- src/main/deploy/robotConfigs/SBSD/swervedrivetrain.conf
- src/main/java/frc/robot/Config4905.java
- src/main/java/frc/robot/utils/PoseEstimation4905.java
> Sbsd initial setup
